// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ntXDjcMXBr--UC789Z8i04WNj-VvAas',
    appId: '1:901420758255:web:69868422da593934e3d71a',
    messagingSenderId: '901420758255',
    projectId: 'ten-mins-five-ingredients',
    authDomain: 'ten-mins-five-ingredients.firebaseapp.com',
    storageBucket: 'ten-mins-five-ingredients.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADWsgTko-tKUTTheIRTYBpy9kfMLRzqpo',
    appId: '1:901420758255:android:d4806f0beebe9754e3d71a',
    messagingSenderId: '901420758255',
    projectId: 'ten-mins-five-ingredients',
    storageBucket: 'ten-mins-five-ingredients.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEyJcRJmS-pXVmCf3aS-Eeql8LNxrGkH8',
    appId: '1:901420758255:ios:fbd6c44bb1eceb24e3d71a',
    messagingSenderId: '901420758255',
    projectId: 'ten-mins-five-ingredients',
    storageBucket: 'ten-mins-five-ingredients.appspot.com',
    iosBundleId: 'com.tenminsfiveingredients.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEyJcRJmS-pXVmCf3aS-Eeql8LNxrGkH8',
    appId: '1:901420758255:ios:fbd6c44bb1eceb24e3d71a',
    messagingSenderId: '901420758255',
    projectId: 'ten-mins-five-ingredients',
    storageBucket: 'ten-mins-five-ingredients.appspot.com',
    iosBundleId: 'com.tenminsfiveingredients.app',
  );
}
